name: PocketWeb
main: PocketWeb\Main
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
author: MegaSamNinja
description: sends a user the servers website
commands:
 website:
  description: Tells the server website
  usage: /website
